---
name: Tika-Gotenberg
version: dev
slug: tika-gotenberg
url: https://github.com/BenoitAnastay/tika-gotenberg-home-assistant-addon
init: false
ingress: false
ingress_stream: false
panel_icon: mdi:leaf
panel_admin: false
homeassistant_api: false
hassio_api: false
description:
  An extension for paperless addon to use Tika and Gotenberg
arch:
  - aarch64
  - amd64
startup: system
ports:
  3000/tcp: null
  9998/tcp: null
ports_description:
  3000/tcp: Gotenberg
  9998/tcp: Tika
